### ISSUE TITLE
Export Collections to BigQuery creates identical entries in raw_changelog if multiple documents are created at the same time by a batch

### ISSUE THREAD

**Issue by jonathanrose9** [firebase/extensions#101]
### Configuration
- Extension name: **Export Collections to BigQuery**

### The problem

Is it a problem to use the function in combination with batch operations and multiple documents in Firestore? Thank you very much for your help!

#### Steps to reproduce:
  - The extension is configured twice in the same Firebase project
  - We do not use wildcards in both configurations of the extension.
  - The two configurations of the extension each point to a sub-collection. (Collection path1: collection/doc1/subcollection; Collection path2: collection/doc2/subcollection)
  - The two configurations store the events in the same BigQuery dataset but in different tables within the dataset.
  - In our case, there are two ways in which documents are created in the subcollections: 
    - Documents in the sub-collections can be created separately by batch. The command batch.set() is used for this, because in this case the parent document is also updated.
    - Multiple documents in the sub-collections can be created per batch. The command batch.set() is used for this. The number can reach the maximum of 500 available from Firestore (see: https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes).

##### Expected result
For each created document in the sub-collection, an event in BigQuery should be stored in the raw_changelog table. There should be no duplicate entries.

##### Actual result
Multiple documents are created by a batch process in Firestore in the subcollections (as described above). The background trigger of the function starts as desired for each new document and exports the new documents as an event with the operation: "Create" to BigQuery. When we query the latest view table we get the expected result and the current state of the documents in Firestore. If you look at the raw_changelog table in BigQuery, some of the create operation entries are doubled. For some entries that were previously loaded into Firestore by batch, document_name, timestamp, event_id, operation and data are identical. If the batch process is executed with a small number of documents ( <10 ), no duplicate entries are created in Firestore. If the batch process is executed with a high number (e.g.: 400), identical entries (max. 2 per document) are created for some documents.

**Comment by rphlmr** [comment]
Hi,
We have 3 bigquery extensions running (each one on different collections, no subcollections) and we didn't notice duplicating data.
Maybe the duplication is due to retries made by your function executing batch (there is a limitation of 1s to write on the same document).
You said that your batch processing write on the parent document, for this use case I would use transaction instead of batch.
Transaction will stop and retry if the parent document changed since the transaction's start.

**Comment by jonathanrose9** [comment]
Hello rphlmr,

Thank you very much for your answer! We do not use IDs automatically generated by Firestore for the documents affected by the extension. In our case I can therefore say that if it happens that several documents are processed with one batch, always new documents with a new ID are created. So it cannot happen that the same document is written to. Or does the batch process perform repeated create operations? So if we use a batch with 500 accesses to documents, and the document ID does not exist yet, the command batch.set() creates a new document, right? 

Thanks in advance for your answers!

**Comment by karayu** [comment]
@IanWyszynski do you mind taking a look?

**Comment by IanWyszynski** [comment]
>If you look at the raw_changelog table in BigQuery, some of the create operation entries are doubled. For some entries that were previously loaded into Firestore by batch, document_name, timestamp, event_id, operation and data are identical. If the batch process is executed with a small number of documents ( <10 ), no duplicate entries are created in Firestore. If the batch process is executed with a high number (e.g.: 400), identical entries (max. 2 per document) are created for some documents.

Since the event_id column is duplicated, I suspect this behavior is due to the at-least-once semantics of events https://cloud.google.com/functions/docs/concepts/events-triggers. There is a trade-off here between querying the raw changelog (which can potentially grow large) for conflicting event_ids _on each function invocation_ and simply duplicating data that is filtered out in the latest view of the raw changelog. We chose the latter approach as multiple function executions don't happen frequently enough to justify doubling the number of requests sent from this extension to bigquery.

We could investigate setting the `insertId` property for our BigQuery streaming insert call to the `eventId` of the currently executing function. This would at least prevent duplicated data in the event that duplicate functions are executed within 1 minute of each other, but this still may not capture all cases. I'll open a PR with this change.

**Comment by karayu** [comment]
Closing since the PR is merged
