### ISSUE TITLE
[firestore-bigquery-export] Table not partitioned despite using default _PARTITIONTIME pseudo column

### ISSUE THREAD

**Issue by guneemwelloeux** [firebase/extensions#1293]
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your configuration

Extension name: firestore-bigquery-export
Extension version: `0.1.26
Configuration values (redact info where appropriate):
Cloud functions location: europe-west-1
BigQuery Dataset location: eu
Collection path: users
Dataset ID: firestore_export
Table ID: users
BigQuery SQL table Time Partitioning option type: DAY
BigQuery Time Partitioning column name: <LEFT EMPTY ON PURPOSE>
Firestore Document field name for BigQuery SQL Time Partitioning field: <LEFT EMPTY ON PURPOSE>
BigQuery SQL Time Partitioning table schema field(column) type: TIMESTAMP

Steps to reproduce:
Configure the extension with ANY combination of partitioning options. Simply specifying the BigQuery SQL table Time Partitioning option type appears to have no effect.

Expected result
After running the script to backfill the table from my Firestore collection I expect to see a partitioned table by MONTH using the 'created' Timestamp field from each 'sales' document ingested.

#### Steps to reproduce:

Configure the extension specifying partitioning by DAY, with a TIMESTAMP type, but no firestore field or BigQuery field.
The table is created without partitioning, despite the setting explicitly requesting one

##### Expected result
According to the description of the BigQuery field for partitioning, when left empty, the pseudo column _PARTITIONTIME should be used, therefore creating a partition on Ingestion time, rather than mapping one of the fields from the firestore document.
We don't use the native firestore timestamp type for interoperability, so we can't map that to BigQuery.
However, partitioning by ingestion time should still be possible, to reduce costs on the BQ side.

##### Actual result
The table is not partitioned.

**Comment by cabljac** [comment]
Added to under consideration, thanks! Will investigate this asap.

**Comment by soarb** [comment]
HI @cabljac I also have two open issues on this issue, #1039 and #1059.

@dackers86 offered to re-test and get back to me with some examples but I haven't heard anything yet. Basically no matter what partitioning options I set, a partitioned table is _not_ created.

Our queries over this table are to provide weekly sales data, but as it's not partitioned and we have several years worth of data now, the queries are starting to take a significant amount of time (and I daresay cost) to perform.

Any updates would be greatly appreciated!

**Comment by cabljac** [comment]
Hey! Apologies for the late response here.

Am I right in thinking `Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional)` is left empty here?

**Comment by soarb** [comment]
No worries @cabljac! 

As you can see it's been a while since I raised the issue and we've just been living with the none partitioned table for almost a year now. The problem really was that the extension wouldn't create a partitioned table no matter what combination of partitioning options I tried. 

I was hoping for a working example of how to do this, as I personally found the docs for the partitioning options a little confusing! 

We wanted to partition on a specific Firestore Document field name (which IS a Timestamp type field), but also tried the most basic ingestion time partitioning option. In all cases during backfill, the table created was not partitioned.

Referring to this closed issue #621 we've _always_ seen this in the log entries when attempting to backfill the table:-

`{"severity":"INFO","message":"Creating BigQuery dataset: firestore_stream_v2"} {"severity":"INFO","message":"Created BigQuery dataset: firestore_stream_v2"} {"severity":"INFO","message":"Creating BigQuery table: sales_raw_changelog"} {"severity":"WARNING","message":"No valid table reference is available. Skipping partitioning"} {"severity":"WARNING","message":"Cannot partition an existing table firestore_stream_v2_sales_raw_changelog"} {"severity":"WARNING","message":"Cannot partition an existing table firestore_stream_v2_sales_raw_changelog"} {"severity":"INFO","message":"Clustering removed on sales_raw_changelog"} {"severity":"INFO","message":"Created BigQuery table: sales_raw_changelog"} {"severity":"WARNING","message":"No valid table reference is available. Skipping partitioning"} {"severity":"WARNING","message":"Cannot partition an existing table firestore_stream_v2_sales_raw_latest"}`

**Comment by cabljac** [comment]
What i'm thinking is if the option `Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional)` was left empty when the table was first created, then it might have been impossible to later partition the table

**Comment by cabljac** [comment]
If you create another installation of the extension with that parameter set, but a different table name, do you run into the same issue?

**Comment by soarb** [comment]
OK my first confusion over all these (optional) options is what is and isn't optional :)

I assume setting the "Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional)" field is pointless if I don't also set the "BigQuery SQL table Time Partitioning option type (Optional)" field?

Is this correct?

**Comment by cabljac** [comment]
Yeah this is an issue which should be solved in the future - What we really need are "conditional" params, because although some params are optional, there can be dependencies between them

> I assume setting the "Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional)" field is pointless if I don't also set the "BigQuery SQL table Time Partitioning option type (Optional)" field?

I think so, or at least if you have one, you need the other. 

<img width="930" alt="Screenshot 2023-01-12 at 11 27 15" src="https://user-images.githubusercontent.com/32874567/212055081-12d5e6cf-9425-45d0-bf38-8247853a0491.png">

<img width="718" alt="Screenshot 2023-01-12 at 11 31 21" src="https://user-images.githubusercontent.com/32874567/212055809-3e7341aa-18c2-4fd0-b9ea-1075ecdc52ec.png">

**Comment by soarb** [comment]
Cool. So I've configured the extension to stream to a new data set. Have set the BigQuerl SQL Time Partitioning field to "Month" and set my Firestore Document field to a top level Firestore Timestamp field.

As expected, there's nothing in BigQuery yet, as no updates have been made to the target collection and I'm about to backfill to it so please bear with me!

**Comment by cabljac** [comment]
Cool :) yeah if that timestamp field is populated, it should (i hope) import it to BQ and partition

**Comment by soarb** [comment]
This is how I configured the extension ... at least the partitioning options. 

Just a little concerned I didn't specify anything for the following fields:-

- "BigQuery Time Partitioning column name"
-  "BigQuery SQL Time Partitioning table schema field(column) type"

Although I'm hoping there's a default for leaving the "BigQuery Time Partitioning column name" field empty?

 

![Screenshot 2023-01-12 at 11 42 20](https://user-images.githubusercontent.com/316338/212058314-20e3fdaf-046d-478c-95cf-898cc247caa6.png)

**Comment by soarb** [comment]
Ok so running the backfill script with these options:-

? What is your Firebase project ID? ****

? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you plan to mirror changes.) sales

? Would you like to import documents via a Collection Group query? No

? What is the ID of the BigQuery dataset that you would like to use? (A dataset will be created if it doesn't already exist) firestore_monthly_sales_stream

? What is the identifying prefix of the BigQuery table that you would like to import to? (A table will be created if one doesn't already exist) sales

? How many documents should the import stream into BigQuery at once? 300

? Where would you like the BigQuery dataset to be located? eu

? Would you like to run the import across multiple threads? No

? Would you like to use the new optimized snapshot query script? Yes

? Would you like to use a local firestore emulator? No

Results in the same problem:-

Importing data from Cloud Firestore Collection: sales, to BigQuery Dataset: firestore_monthly_sales_stream, Table: sales_raw_changelog
{"severity":"INFO","message":"Creating BigQuery dataset: firestore_monthly_sales_stream"}
{"severity":"INFO","message":"Created BigQuery dataset: firestore_monthly_sales_stream"}
{"severity":"INFO","message":"Creating BigQuery table: sales_raw_changelog"}
{"severity":"WARNING","message":"No valid table reference is available. Skipping partitioning"}
{"severity":"WARNING","message":"Cannot partition an existing table firestore_monthly_sales_stream_sales_raw_changelog"}
{"severity":"WARNING","message":"Cannot partition an existing table firestore_monthly_sales_stream_sales_raw_changelog"}
{"severity":"INFO","message":"Clustering removed on sales_raw_changelog"}
{"severity":"INFO","message":"Created BigQuery table: sales_raw_changelog"}
{"severity":"INFO","message":"Creating BigQuery view: sales_raw_latest\nQuery:\n-- Retrieves the latest document change events for all live documents.\n--   timestamp: The Firestore timestamp at which the event took place.\n--   operation: One of INSERT, UPDATE, DELETE, IMPORT.\n--   event_id: The id of the event that triggered the cloud function mirrored the event.\n--   data: A raw JSON payload of the current state of the document.\n--   document_id: The document id as defined in the Firestore database\nWITH latest AS (\n  SELECT\n    max(timestamp) as latest_timestamp,\n    document_name\n  FROM\n    `net-go-dev.firestore_monthly_sales_stream.sales_raw_changelog`\n  GROUP BY\n    document_name\n)\nSELECT\n  t.document_name,\n  document_id,\n  timestamp as timestamp,\n  ANY_VALUE(event_id) as event_id,\n  operation as operation,\n  ANY_VALUE(data) as data,\n  ANY_VALUE(old_data) as old_data\nFROM\n  `net-go-dev.firestore_monthly_sales_stream.sales_raw_changelog` AS t\n  JOIN latest ON (\n    t.document_name = latest.document_name\n    AND (\n      IFNULL(t.timestamp, timestamp(\"1970-01-01 00:00:00+00\"))\n    ) = (\n      IFNULL(\n        latest.latest_timestamp,\n        timestamp(\"1970-01-01 00:00:00+00\")\n      )\n    )\n  )\nWHERE\n  operation != \"DELETE\"\nGROUP BY\n  document_name,\n  document_id,\n  timestamp,\n  operation"}
{"severity":"INFO","message":"Created BigQuery view: sales_raw_latest"}
{"severity":"INFO","message":"Inserting 300 row(s) of data into BigQuery"}
{"severity":"INFO","message":"Inserted 300 row(s) of data into BigQuery"}
{"severity":"INFO","message":"Inserting 5 row(s) of data into BigQuery"}
{"severity":"INFO","message":"Inserted 5 row(s) of data into BigQuery"}

**Comment by soarb** [comment]
It's always this line that confuses me: {"severity":"WARNING","message":"No valid table reference is available. Skipping partitioning"}

but at no point am I instructed to ensure the table is available, and indeed the dataset AND table are not created UNTIL I run the script?

**Comment by cabljac** [comment]
> Although I'm hoping there's a default for leaving the "BigQuery Time Partitioning column name" field empty?

I believe this defaults to `_PARTITIONTIME`

**Comment by cabljac** [comment]
having a go at replicating this now

**Comment by soarb** [comment]
Thanks, really appreciate it!

So in reference to log output, I really don't understand what it is I'm doing wrong?

- Install and configure the extension. Choose a dataset name, table name, Firestore collection name and document field for partitioning.
- Set additional partitioning options
- Run the backfill script setting these same values as response to each question.

Result > No valid table reference available. Skipping partitioning.

There must be something critical I'm missing or misunderstood :(

**Comment by cabljac** [comment]
The only thing i can think is that the table has to be created by the stream before running the import script for the partitioning to work, but im not sure

**Comment by soarb** [comment]
Agreed, but in the docs it states that you _must_ backfill before doing anything else?

> Backfill your BigQuery dataset
This extension only sends the content of documents that have been changed – it does not export your full dataset of existing documents into BigQuery. So, to backfill your BigQuery dataset with all the documents in your collection, you can run the [import script](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md) provided by this extension.

Important: Run the import script over the entire collection after installing this extension, otherwise all writes to your database during the import might be lost.

**Comment by soarb** [comment]
... but of course what you're saying makes sense too! Maybe if I install the extension again and force an update on one of the collection's documents first, check if the dataset and table get created _then_ backfill it? In which case it's more of a documentation issue albeit a bit tricky to get the ordering of things right :)

**Comment by cabljac** [comment]
if that's the case then i think we should look into fixing it so it doesn't require that flow, it seems like a workaround to me

if you're able to try that and it works, let me know, and i can look into fixing it perhaps - i will continue to investigate as well

**Comment by soarb** [comment]
no worries, I'll give that a go and get back to you, thanks again!

**Comment by cabljac** [comment]
from what i understand, there is a PR to allow the extension will use Lifecycle Events, which _should_ resolve this workaround

**Comment by soarb** [comment]
OK, just deleted the dataset and all sub entities created i.e., tables, views etc from BigQuery.

Reconfigured the extension in our Firebase project and then, rather than backfilling the table with the script, wrote a new record to our collection.

The streaming extension did create the dataset and underlying table and view, but still the table is NOT partitioned so I'm at a complete loss here :(

**Comment by soarb** [comment]
Yep. Re-configured again to try a different set of partitioning options. Every time, the streaming extension creates a non partitioned table. It's either ignoring the options or failing to create one for whatever reason.

**Comment by cabljac** [comment]
yeah reproduced that i think. looking into it :)

**Comment by cabljac** [comment]
I had set the partition column parameter, ill attempt without setting that next

**Comment by soarb** [comment]
I think today I've come to the conclusion that either I don't know what I'm doing with the options on configuration or they just simple don't work. I'm getting to the point now where I'm just randomly trying different combinations of options and none of them generate a partitioned table so really could do with some insight as to whether there's some different in our setup or I'm just using the extension incorrectly :(

**Comment by cabljac** [comment]
we could chat in the extensions channel of the invertase discord server, we might be able to provide better support there?

https://discord.gg/k3E2vKRg

**Comment by cabljac** [comment]
We have a discord server if you'd like to chat in realtime and figure this issue out together: invertase.link/discord

**Comment by soarb** [comment]
Brilliant! Are you about tomorrow after 10am? Will try and catch you on the discord server if that's OK?

**Comment by soarb** [comment]
> If it helps, we could chat more in realtime and figure this out together on the Invertase discord server;: [invertase.link/discord](https://invertase.link/discord)

@cabljac thanks for all your help with this so far - I've joined the discord channel and introduced myself - happy to carry the conversion on there in the Firebase Extensions channel :)
