### ISSUE TITLE
[firestore-bigquery-export] Better error logging on bigquery extension when partition is set to none

### ISSUE THREAD

**Issue by elvisun** [firebase/extensions#1368]
### Describe the problem
We have a firebase customer trying to set up the bigquery extension and is confused because they have partition option set to `none`, but still getting warnings: `Cannot partition an existing table ${table.dataset.id}_${table.id}`.

Looking at the code it might be because this line logs a warning regardless of the partitioning settings.
https://github.com/firebase/extensions/blob/fdbf5004c8d5e7b9749bbab3b2e16950ad812007/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L131

The customer is asking if they can avoid these warning logs, so I wonder if we should have better logging/messaging here?

**Comment by dackers86** [comment]
This is definitely something we should look into, this can be done through:

 - Improved messages
 - Verbose messaging

Or a combination of both, maybe.

**Comment by adamkeys** [comment]
It would seem that there is a deeper issue here. Firstly, per the definition of `bigquery.Table`, exists()` returns a `Promise`, thus will always evaluate as being truthy here:

https://github.com/firebase/extensions/blob/41d9a3b5e46487d725c6bdd8c2f6ad1f0d438d7a/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L132-L137

In fact, to emphasize, the same method is called again in the following statement with `await`:

https://github.com/firebase/extensions/blob/41d9a3b5e46487d725c6bdd8c2f6ad1f0d438d7a/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L139

Additionally, the comment "No table provided, cannot evaluate" does not seem to correspond with the logic that follows. It appears to actually be in reference to the previous line.

Lastly, the content of the log message indicates that the table cannot be partitioned, but the scope of the method is only to check if the table has already been partitioned. These are conflicting concerns.

I suspect that said block of code was mistakenly included here and that the errant logging brought forward in this issue is a result of that, not due to the logging of it in general.

**Comment by samatcolumn** [comment]
We're also experiencing a ton of logs related to partitioning even though we do not have partitioning configured.
