### ISSUE TITLE
Arrays Wrapped in Double Quotes When Imported to BQ

### ISSUE THREAD

**Issue by whitwhitgraham** [firebase/extensions#1536]
[REQUIRED] Step 2: Describe your configuration
Extension name: firestore-bigquery-export
Extension version: 0.1.31

[REQUIRED] Step 3: Describe the problem
String values in bigquery are wrapped in extra double-quote characters. So you'll see "foo" in bigquery instead of foo.

Steps to reproduce:
Import array data into bigquery that has string values.
Query in BQ.

Expected result
The string values are the values in bigquery.
ex: "array1": ["D12Gy5ulS1PJCvaiOeH2nD8ZG0k2", "X1561Hu54QNul7POt3L37uh2d7e2"]

Actual result
The strings get an extra double-quote character (") at the start, and one at the end too.
ex: "array1": ["\"D12Gy5ulS1PJCvaiOeH2nD8ZG0k2\"", "\"X1561Hu54QNul7POt3L37uh2d7e2\""]

**Comment by cabljac** [comment]
Hi there, I think this has since been fixed, likely in `v0.1.34`. I'm happy to reopen if this issue still occurs, but closing for now:

for example:

<img width="352" alt="Screenshot 2023-11-15 at 12 44 42" src="https://github.com/firebase/extensions/assets/32874567/c018c045-f324-4bd3-9c4e-f9553c961c14">

and reflected in bigquery:

<img width="412" alt="Screenshot 2023-11-15 at 12 44 58" src="https://github.com/firebase/extensions/assets/32874567/7a97a80e-ebcf-4649-927d-89e365fb3953">
