### ISSUE TITLE
[storage-resize-images] Support for HEIC format

### ISSUE THREAD

**Issue by alexanderserraris** [firebase/extensions#1572]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`storage-resize-images`)

### What feature would you like to see?

Describe the feature you would like to add, or how you'd like to see the extension change.

The extensions currently supports resizing images in JPEG, PNG, WebP, GIF, AVIF and TIFF formats. We should add support for resizing the HEIC format.

### How would you use it?

Tell us how you'd use this feature in your app.

I'm using the `storage-resize-images` extension to resize profile pictures of users, for showing thumbnails. Multiple users are using iPhone and are uploading a HEIC image as a profile picture. It would be nice if the extension resizes these aswell.

**Comment by jauntybrain** [comment]
Hi @alexanderserraris, thank you for reporting this issue.

Unfortunately, due to **HEIC** being a patented format, not many libraries include it. Since we are using **Sharp** for image resizing, [this issue](https://github.com/lovell/sharp/issues/1105) highlights that implementing HEIC support with that library will require a big workaround which, I'm afraid, might cause problems with the Cloud Functions deployment.

Therefore, closing this until further updates from Sharp.
