### ISSUE TITLE
🐛 [firestore-bigquery-export] Change log table is not created.

### ISSUE THREAD

**Issue by RyosukeNishi** [firebase/extensions#1829]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.38**
- Configuration values (redact info where appropriate):
<img width="642" alt="スクリーンショット 2023-11-24 17 42 24" src="https://github.com/firebase/extensions/assets/46443906/9c146897-be31-4d96-aed6-0905469b95aa">
<img width="646" alt="スクリーンショット 2023-11-24 17 42 33" src="https://github.com/firebase/extensions/assets/46443906/9e810591-a704-4ca0-8b68-496892ce5800">
<img width="644" alt="スクリーンショット 2023-11-24 17 42 42" src="https://github.com/firebase/extensions/assets/46443906/82df58ff-1f3c-4c67-89c7-482702374588">

#### Steps to reproduce:
Install the extension with the parameters above.

##### Expected result
A table named `bookmarks_raw_changelog` is created.

##### Actual result
It is not.

**Comment by cabljac** [comment]
I tried to reproduce this just now and it created the table? Did the extension complete installation otherwise? Were there any relevant logs in the initBigQuerySync function?

<img width="516" alt="Screenshot 2023-11-24 at 09 23 24" src="https://github.com/firebase/extensions/assets/32874567/a6789915-cc6b-46d7-a335-066cced7b13d">

**Comment by RyosukeNishi** [comment]
I found logs like this.
<img width="754" alt="スクリーンショット 2023-11-24 18 31 18" src="https://github.com/firebase/extensions/assets/46443906/e0e034f1-b8ca-4558-b253-7e4a72c97e58">

**Comment by RyosukeNishi** [comment]
`Runtime Status` does not change from `Processing` for more than 30 mins.
<img width="754" alt="スクリーンショット 2023-11-24 18 31 18" src="https://github.com/firebase/extensions/assets/46443906/ee26d4b4-6e03-4510-bd55-262c07a17a87">

**Comment by RyosukeNishi** [comment]
@cabljac

**Comment by RyosukeNishi** [comment]
I also got this error.
<img width="1071" alt="スクリーンショット 2023-11-24 18 40 30" src="https://github.com/firebase/extensions/assets/46443906/e850ac13-9ada-4e7e-8b3b-8d0d9e175dff">

**Comment by RyosukeNishi** [comment]
After waiting for about 30 mins, the table was finally created, but time partitioning is not enabled.

**Comment by cabljac** [comment]
OK yea, there will be a delay especially if installing a fresh instance, as lifecycle hooks require IAM roles to be applied so that tasks go through. With regards to the time partitioning, I'll track that here https://github.com/firebase/extensions/issues/1819 , it's a known issue and a solution is in progress. Thanks! Closing this for now
