### ISSUE TITLE
🐛 [firestore-send-email] The default "From" email is not respected

### ISSUE THREAD

**Issue by zjamshidi** [firebase/extensions#1938]
### Describe your configuration

- Extension name: `firestore-send-email`
- Extension version: 0.1.30
- Configuration values (redact info where appropriate):
<img width="373" alt="Screenshot 2024-01-30 at 6 42 04 PM" src="https://github.com/firebase/extensions/assets/3742220/1c804713-67e8-4f8b-95ab-64ac2cac0cc6">

### Describe the problem
It doesn't matter if I set the "FROM" field in the document or not, the received emails are always from info@ email. Neither the value in the "FROM" field of the document nor the default FROM email in the configuration is respected.

<img width="534" alt="Screenshot 2024-01-30 at 6 25 36 PM" src="https://github.com/firebase/extensions/assets/3742220/4cc8b7dc-67f7-44db-8e59-1d8a3e1ac137">

**Comment by jauntybrain** [comment]
Hi @zjamshidi,

As per `nodemailer` [documentation](https://nodemailer.com/usage/using-gmail/#:~:text=Gmail%20also%20always,the%20authenticated%20user.), Gmail does not support `from` address:

> Gmail also always sets authenticated username as the From: email address. So if you authenticate as [foo@example.com](mailto:foo@example.com) and set [bar@example.com](mailto:bar@example.com) as the from: address, then Gmail reverts this and replaces the sender with the authenticated user.

Since this extension uses nodemailer to send emails, unfortunately, it's impossible to specify a custom `from` address when using Gmail SMTP. We will make sure to update the documentation to reflect this.
