### ISSUE TITLE
Delete User Data Deprecated API usage

### ISSUE THREAD

**Issue by ccjernigan** [firebase/extensions#206]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: delete-user-data
- Extension version: 0.1.3

### [REQUIRED] Step 3: Describe the problem
I am getting emails from Google Cloud Platform stating that I am using a deprecated API. The attached information points to this Firebase extension.

The email starts with "Our records show that you own projects with App Engine applications or Cloud Functions that are still calling the pre-GA v0.1 and v1beta1 endpoints of the App Engine and Cloud Functions metadata server."

And it specifically points to "ext-delete-user-data-clearData"

**Comment by laurenzlong** [comment]
I dug into this a bit more and it is due to the outdated firebase-tools dependency. This extension currently uses firebase-tools 7.5.0, which has a dependency `"google-auto-auth": "^0.7.2",` (see [package-lock.json](**https://github.com/firebase/extensions/blob/next/delete-user-data/package-lock.json#L1842**)). Looking at the git repo for google-auto-auth, v0.7.2 had the dependency ""gcp-metadata": "^0.3.0", (see [here](https://github.com/stephenplusplus/google-auto-auth/blob/0ce5ad9657c82c5264920a473544fca472b4fc74/package.json#L37)). This is lower than the minimum supported library version indicated in https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server#supported-google-libraries. 

So the fix is just to upgrade "firebase-tools" dependency to the latest, which relies on an updated version of "google-auto-auth" and thus an updated version of "gcp-metadata". @Salakar @russellwheatley @Ehesp could one of you please make a PR to update "firebase-tools" and also verify the the extension still works as expected?

**Comment by laurenzlong** [comment]
@ccjernigan To confirm my understanding of the impact of this, can you verify whether or not you use this extension to delete data from Firestore?

**Comment by ccjernigan** [comment]
@laurenzlong I am using this extension to delete data from both Firestore and Firebase Storage.

**Comment by Ehesp** [comment]
I've upgraded `firebase-tools` and can confirm things are working as expected:

![image](https://user-images.githubusercontent.com/842078/76418945-70172d00-6397-11ea-89c9-3071dc946f65.png)

I'll get a PR up.
