### ISSUE TITLE
Update extensions to Node 10

### ISSUE THREAD

**Issue by sk-** [firebase/extensions#327]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `firestore-bigquery-export`

### What feature would you like to see?

Please add support for the Node 10 runtime environment, now that it reached GA, and the Node 8 environment will be deprecated.

See this email we recently got:
> The Node.js 10 runtime on Cloud Function has now reached General Availability and the Node.js 8 runtime on Cloud Functions will be deprecated. To avoid potential disruptions or security risks, you should update your functions to Node.js 10. 

### How would you use it?

Tell us how you'd use this feature in your app.

**Comment by russellwheatley** [comment]
Hey @sk-, thanks for the suggestion. I think the upgrade to v10 is already in the pipeline 😄

**Comment by karayu** [comment]
Thanks so much for the feedback SK! We will be rolling out Node 10 updates for every extension in the next couple months and will be sending you a follow-up message when that's ready. Don't worry, you'll have plenty of time to update before the Node 8 deadline of Feb 2021.

**Comment by sk-** [comment]
@karayu Thanks for replying, but a couple of months is not a good sign at all for an officially supported product.

I think the relevant date is June 5.

> June 5, 2020: Node.js 8 runtime will be deprecated on Cloud Functions. You can continue to create new functions and update existing functions that use Node.js 8. However, this is not recommended since functions using Node.js 8 will no longer receive security updates.

Note that the current status of Node 8, which is EOL means that neither the NodeJs foundation neither Google (starting on June 5) will patch any security issues.

Could you share a public issue tracking this feature?

**Comment by CyrusZei** [comment]
so, I just upgraded my cloud functions to use node 10, but why can't I upgrade my extensions to use node 10?

**Comment by mbleigh** [comment]
Hi folks, just wanted to give a little context here. If it were a simple technical matter of "upgrade to Node 10" we'd have already done it as soon as Node 10 went GA.

However, because of the billing changes that are coming soon for Node 10 (requiring a Blaze plan), we need to be careful in how we migrate extensions that currently work on the Spark plan. This is a high-priority item for the team, but again one that requires some care to address.

I am going to raise the idea of migrating extensions that already require a billing account (due to external network calls or integrations with billing-required GCP services) as that might be more straightforward. You can consider this the public issue tracker for migrating extensions to Node 10, we'll keep communicating on here.

**Comment by rosariopfernandes** [comment]
Can we pin this issue to the issues page? It might be helpful to prevent newcomers from opening new issues with the same suggestion.

**Comment by houdayec** [comment]
Upgrade to Node 10 is now available!
