### ISSUE TITLE
firestore-counter - call from cloud function

### ISSUE THREAD

**Issue by cjmconie** [firebase/extensions#342]
### [READ] Step 1: Are you in the right place?

Yes, this is feature request for an extension to the `firestore-counter` to be available for use in a cloud function. Currently the [Web](https://github.com/firebase/extensions/blob/master/firestore-counter/clients/web/src/index.ts) client code can't be used as-is since it relies on the `document` object (see related questions below).

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** `firestore-counter`

### What feature would you like to see?

A server-side shared counter, which can be invoked from a cloud function. 

I have looked at the example client code for [Web](https://github.com/firebase/extensions/blob/master/firestore-counter/clients/web/src/index.ts) and [Android](https://github.com/firebase/extensions/blob/master/firestore-counter/clients/android/src/main/java/com/firebase/firestore/counter/FirestoreShardedCounter.java), and the feature request for [iOS](https://github.com/firebase/extensions/issues/299).

### How would you use it?

I have a requirement that states that a "like" counter can only be updated once per user. This means I need to perform a check before invoking the shared counter. The best way I can think of is using a cloud function (please feel free to explain if there is a better approach - I am new to Firebase).

### Related Questions

(I'm not sure if this is the right place to ask these questions, however they are directly related to this feature request).

The client code for  [Web](https://github.com/firebase/extensions/blob/master/firestore-counter/clients/web/src/index.ts)  and [Android](https://github.com/firebase/extensions/blob/master/firestore-counter/clients/android/src/main/java/com/firebase/firestore/counter/FirestoreShardedCounter.java) differ in the way they compute the `shardId`:

Android
```java
this.shardId = UUID.randomUUID().toString();
```

Web
```js
function getShardId(cookie: string): string {
  const result = new RegExp(
    "(?:^|; )" + encodeURIComponent(cookie) + "=([^;]*)"
  ).exec(document.cookie);
  if (result) return result[1];

  const shardId = uuid.v4();

  const date = new Date();
  date.setTime(date.getTime() + 30 * 24 * 60 * 60 * 1000);
  const expires = "; expires=" + date.toUTCString();

  document.cookie =
    encodeURIComponent(cookie) + "=" + shardId + expires + "; path=/";
  return shardId;
}
```

1. Why does the Android code use a simple UUID and the Web code a more complex function involving a cookie string?
1. We would like to create our own version of this server-side shared counter - how should we go about creating the shardId in this context?

**Comment by karayu** [comment]
Patryk, do you have any thoughts on this?

**Comment by lepatryk** [comment]
Hi Cameron,

Thank you for your question. There are many concerns here, I'll try to unpack them all and address one by one.

> 1. Why does the Android code use a simple UUID and the Web code a more complex function involving a cookie string?

Both of these clients are just samples and not all implemented with the same functionality. Web tries to persist uuid in the cookie, Android regenerates uuid at each instantiation, which is less ideal.

The idea behind persisting UUID is to make the shard name stable and improve user experience in case [firestore offline mode](https://firebase.google.com/docs/firestore/manage-data/enable-offline) is turned on. Without it, if application is restarted (or webapp refreshed), the latest increment (that may be still pending) will disappear from the counter until it is synced with the server.

If your users are logged in, you can also use their unique userId from Firebase Auth as a shard name. This option is the simplest and gives additional benefits in security rules. You know which shard each user should be updating and you can enforce it in rules (see below for an example).

> 2. We would like to create our own version of this server-side shared counter - how should we go about creating the shardId in this context?

For the server-side client, persisting UUID doesn't make sense and you may regenerate uuid every time:
```js
function getShardId(cookie: string): string {
  return uuid.v4();
}
```

To be honest, you don't need any special library for your function code at all. Instead of updating the main document simply increment a shard in a sub-collection, e.g.

```js
// Instead of directly incrementing the field in your document
// db.doc(`sites/MyFavorite`).set({likes: firestore.FieldValue.increment(1)}, {merge: true});
// increment the same field in a shard in _counter_shards_ subcollection.
db.doc(`sites/MyFavorite/_counter_shards_/${uuid.v4()}`).set({likes: firestore.FieldValue.increment(1)}, {merge: true});
``` 

Just beware that the code above is not idempotent and in a rare case that your function is called more than once, the counter will be incremented multiple times!

> I have a requirement that states that a "like" counter can only be updated once per user. This means I need to perform a check before invoking the shared counter. The best way I can think of is using a cloud function (please feel free to explain if there is a better approach - I am new to Firebase).

Cloud function is definitely an option, but there is an alternative that is a bit more idiomatic.

In a nutshell, you track the "likes" in two places, a subcollection tracking all the users that liked the site and the total likes counter in your main doc. You update both places atomically in a batch write and have security rules in place to enforce only one "like" per user. I'll try to explain that in more details below.

Let's assume you have sites that can be liked in `/sites/{site}` collection. Each `site` can be liked and you track who liked it in a sub-collection `/sites/{site}/likes/{userId}` that stores empty documents -- markers who likes what. You also have a counter `total_likes` in each site containing a sum.

Here's an example data containing one site "HelloWorld" with 3 likes from users: userId1, userId2 and userId3.

```js
/sites/HelloWorld {"body": "My first page", "total_likes": 3}
/sites/HelloWorld/likes/userId1 {}
/sites/HelloWorld/likes/userId2 {}
/sites/HelloWorld/likes/userId3 {}
```

You know if a given user likes a site or not, by listening to an existence of their like document.

```js
let userId = firebase.auth().currentUser.uid;
db.doc(`/sites/${site}/likes/${userId}`).onSnapshot(function(doc) {
     if (doc.exists) {
        // user likes this site, change the button to "unlike"
     } else { 
       // user doesn't know they like this site yet, set the button to "like"
     }
});
```

The code when the "like" button (or "unlike" button) is clicked boils down to:

```js
let userId = firebase.auth().currentUser.uid;

const likeRef = db.doc(`/sites/${site}/likes/${userId}`);
const counterRef = db.doc(`/sites/${site}/_counter_shard_/${userId}`);

// On "like" click
db.batch()
  .set(likeRef, {})
  .set(counterRef, {total_likes, firestore.FieldValue.increment(1)}, {merge: true})
  .commit();

// On "unlike" click
db.batch()
  .delete(likeRef)
  .set(counterRef, {total_likes, firestore.FieldValue.increment(-1)}, {merge: true})
  .commit();
```

Please note that I'm using `userId` as a shard name in the snippet above. This is intentional as it will simplify security rules for this logic.

The hardest part is to write security rules to enforce one like per user. I took a stab at it and included a rough proposal below. Just beware I didn't test it thoroughly, use any of it at your own risk.

```js
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /sites/{site} {
        match /_counter_shards_/{shardId} {
            function isDocCreated(docPath) {
                return !exists(docPath) && existsAfter(docPath);
            }
            function isDocDeleted(docPath) {
                return exists(docPath) && !existsAfter(docPath);
            }
            // Validate that "total_likes" counter is incremented or decremented by 1 only with corresponding
            // change to /likes/{userID} document. This will enforce only one like per user.
            function validIncrement(oldData, newData, userId) {
                let affectsLikesOnly = oldData.diff(newData).affectedKeys() == ["total_likes"].toSet();
                let pathToLikeDoc = /databases/$(database)/documents/sites/$(site)/likes/$(userId);
                let likesDiff = newData.get('total_likes', 0) - oldData.get('total_likes', 0);
                return shardId == userId &&
                    affectsLikesOnly &&
                    ((likesDiff == 1 && isDocCreated(pathToLikeDoc)) ||
                    (likesDiff == -1 && isDocDeleted(pathToLikeDoc)));
            }
            allow read;
            allow create: if validIncrement({}, request.resource.data, request.auth.uid);
            allow update: if validIncrement(resource != null ? resource.data : {}, request.resource.data, request.auth.uid);
        }
        match /likes/{userId} {
            function isAuthorized() {
                return request.auth != null && userId == request.auth.uid;
            }
            // Make sure that "total_likes" counter is updated whenever "like" document is created or deleted.
            // We just have to make sure that the counter is updated. The rule above will make sure the 
            // counter is updated correctly.
            function totalLikesUpdated(shardId) {
                let pathToCounterShard = /databases/$(database)/documents/sites/$(site)/_counter_shards_/$(shardId);
                let oldShardData = exists(pathToCounterShard) ? get(pathToCounterShard).data : {};
                let newShardData = existsAfter(pathToCounterShard) ? getAfter(pathToCounterShard).data : {};
                return newShardData.diff(oldShardData).affectedKeys() == ["total_likes"].toSet();
            }
            allow create: if isAuthorized() &&          // is user authenticated and updating only their like?
                (request.resource.data.size() == 0) &&  // these are just marker docs and should be empty
                totalLikesUpdated(request.auth.uid);    // each like needs to update the counter as well
            // We know the shard name here (same as userId) so we can easily enforce counter increment with each like.
            allow delete: if isAuthorized() && totalLikesUpdated(request.auth.uid);
        }   
    }
  }
}

```

**Comment by i14h** [comment]
Closing this as a solution is already provided without Extensions
