### ISSUE TITLE
Templates should handle attachments

### ISSUE THREAD

**Issue by somejeff** [firebase/extensions#422]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

👍 

### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-send-email

### What feature would you like to see?

It would be great it `templates` could handle `attachments`.

Currently, the `template.ts` returns a `message` object that only includes:
``` javascript
{
  subject: 'Hello {{username}}',
  html: '<b>Welcome {{name}}</b>',
  text: '...',
  amp: ' ... '
}
```

It could also include an array of attachments (in the form of https://nodemailer.com/message/attachments/):
``` javascript
{
  subject: 'Hello {{username}}',
  ...
  attachments: [
    {
      filename: 'Invoice {{invoice_number}}.pdf',
      content: '{{invoice_base64_content}}',
      encoding: 'base64'
  ]
}
```
Then it would use the `data` attribute as usual:
``` javascript
admin.firestore().collection('${param:MAIL_COLLECTION}').add({
  toUids: ['abc123'],
  template: {
    name: 'invoice',
    data: {
      username: 'ada',
      name: 'Ada Lovelace',
      invoice_number: 'Q2020-0001',
      invoice_base64_content: ' ... base 64 encoded binary here ... '
    }
  }
})
```

The result would be an email sent with substituted subject, email contents **and attachments**

### How would you use it?

This would allow us to create templates that have attachments, such as quotes, invoices, progress reports.   
Tools such as html-pdf could be used to create the PDFs
Or URIs,  pretty much anything from https://nodemailer.com/message/attachments/ except filesystem.

**Comment by jhuleatt** [comment]
Thanks for the suggestion @somejeff! 

This is a bit tricky because base64 encoding violates the [Firestore documents should be small](https://firebase.google.com/docs/firestore/best-practices#realtime_updates) rule. However, it looks like NodeMailer allows the `path` to be a url, so we could change the firestore document to something like this so we support a Firebase Storage path instead:

```js
admin
  .firestore()
  .collection("${param:MAIL_COLLECTION}")
  .add({
    toUids: ["abc123"],
    template: {
      name: "invoice",
      data: {
        username: "ada",
        name: "Ada Lovelace",
        invoice_number: "Q2020-0001",
      },
      attachments: [ // new key
        {
          filename: "Invoice-Q2020-0001.txt",
          path: "mystoragebucket/invoices/user1234/", // Firebase Storage path
        },
      ],
    },
  });
```

This does mean that this extension will need to request more permissions on install so that it can access Firebase storage, and we'll need to add logic to download the file from storage and attach it to the email.

@i14h thoughts on this one? Seems like a fair amount of work but doable if we decide to implement it.

**Comment by i14h** [comment]
I think we should add this feature as attachments are a key feature for email sending, @mbleigh what do you think?

**Comment by mbleigh** [comment]
Seems like a reasonable feature request, though I think I'd take it one step at a time. We currently [document](https://github.com/firebase/extensions/pull/158/files) how to send attachments for non-templated email and rather than adding new permissions to the extension (for Cloud Storage) I think we can start by just supporting the same things for templates as well.

How I would think it would work is to store the attachment info in the `template` itself:

```js
{
  text: "Here's the file you requested: {{invoice_name}}"  
  attachments: [
    {
      filename: "{{invoice_name}}.pdf",
      path: "{{invoice_url}}"
    }
  ]
}
```

The idea here is that attachments can be added to the template and will be interpolated with values from `data` just like any of the other parts of the template. To use Cloud Storage with this, the expectation is that you would send along a download URL or other publicly-accessible URL to a file, or provide a full base64 representation in the template if desired.

This is a lightweight approach that (if popular) could be expanded to a full solution for attaching files from GCS, but I'd rather take it one step at a time. @jhuleatt thoughts?

**Comment by jhuleatt** [comment]
Thanks @mbleigh, I didn't realize that we already document attachments in non-templated emails.

Sticking with our existing attachment method but adding template-able attachments sounds good to me.

**Comment by somejeff** [comment]
Nice @mbleigh.  

I understand that interpolating the ```content``` at runtime and attaching it would probably be too heavy, since sizes could get out of hand.

Would we only support the ```path``` attribute?
Could we also support ```href``` and ```httpHeaders``` so that we can protect the files from prying eyes?
```js
{
  text: "Here's the file **only** you requested: {{invoice_name}}" ,
  attachments: [
    {
      filename: "{{invoice_name}}.pdf",
      href: "https://storage.example.com/{{invoice_url}}",
      httpHeaders: {
         authorization: "{{intended_user_jwt}}"
      }
    }
  ]
}
```

**Comment by dackers86** [comment]
@somejeff

These would be able to supported, please see https://nodemailer.com/message/attachments/ for further details
