### ISSUE TITLE
firestore-bigquery-export: Create Column for Each Wildcard in Exported Firestore Path

### ISSUE THREAD

**Issue by phinatic** [firebase/extensions#459]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**

### What feature would you like to see?

When using variable/wildcard path segments in an exported path, I would like to retain the value of those segments in their own columns. This would be helpful in both the raw and in the schema views.

For example `/user/{uid}/post/{postId}`

When exported, only the post is kept in the raw data and the uid can only be used by matching the `document_name` with something like `REGEXP_EXTRACT`

### How would you use it?

I would use these additional columns to perform filtering of the collection based on its parent groups without performing a more expensive regex on the `document_name` itself

**Comment by jhuleatt** [comment]
@phinatic thanks for the request! Filtering on the wildcards is a cool idea, and I've documented how to do it below for my knowledge and others that come across this issue.

Let's double check with @i14h, since the [BigQuery docs](https://cloud.google.com/bigquery/docs/best-practices-performance-compute#avoid_repeatedly_transforming_data_via_sql_queries:~:text=Functions%20like%20regular%20expressions%20require%20additional%20computation), do say "Functions like regular expressions require additional computation", so this may help save cost. But given the complexity this may introduce for the extension (for example, we'd have to update our schema definitions to include these wildcard columns, and would have to think about what happens if the extension is reconfigured with new wildcards for the same path, like  `/users/{uid}/posts/{postId}` -> `/users/{userId}/posts/{postId}`), I don't think we're able to take this feature request on.  

# Filtering by a path's wildcard value

for a wildcard path like this:

```
/users/{uid}/posts/{postId}
```

for document_names that look like this:

```
projects/my-project/databases/(default)/documents/users/phinatic/posts/post1
projects/my-project/databases/(default)/documents/users/jhuleatt/posts/post1
projects/my-project/databases/(default)/documents/users/jhuleatt/posts/post2
```

this query allows filtering by a `uid` that matches `jhuleatt`:

```sql
SELECT *
FROM documents
WHERE REGEXP_CONTAINS(document_name, r"users\/jhuleatt")
```

**Comment by phinatic** [comment]
This is essentially what I have done in the interim until the wildcards are generally available. How do you expect this to effect cost and performance?

**Comment by phinatic** [comment]
For the time being, I have created a view of the table that uses a regex to capture the wildcards into columns. Can this be more easily solved by updating the schema_view scripts rather than the extension itself?

**Comment by phinatic** [comment]
@jhuleatt Any thoughts on just using the regex syntax in the schema views script rather than changing the extension? The script could have us name the wildcard fields and generate the lines above. I can obviously add them by hand, but it would be valuable to standardize and make generally available.

**Comment by jhuleatt** [comment]
@phinatic thank you for the additional feedback. We're not going to take this on at this time, but if we get more requests for this functionality in the future, we will definitely consider it.
