### ISSUE TITLE
storage-resize-images: Resize images by covering the desired dimensions rather than fitting them

### ISSUE THREAD

**Issue by blueyetisoftware-jason** [firebase/extensions#473]
### storage-resize-images

This feature request is for extension: **\storage-resize-images**

### What feature would you like to see?

I would like to be able to specify a strategy to resize the images that will indicate whether the image should cover the target dimensions or fit them. These are analogous to the object-fit property in CSS.

### How would you use it?

I would use it to create images that are guaranteed to fit certain size. The current resize ensures an image doesn't exceed the dimensions, but doesn't guarantee that space will be covered.

**Comment by russellwheatley** [comment]
Hey @phinatic, thanks for the request! I don't have a problem with this request, it is easy enough to implement changes in how images ought to [fit](https://sharp.pixelplumbing.com/api-resize#resize) given dimensions &updating this hardcoded [input](https://github.com/firebase/extensions/blob/next/storage-resize-images/functions/src/index.ts#L178). My slight pause for concern is another input for the user to select. Currently, there are 6 & with this [PR](https://github.com/firebase/extensions/pull/427/files) there will be 8. This feature request will bump it to 9.

What do you think, @jhuleatt?

**Comment by jhuleatt** [comment]
Hey there, the extensions team is still discussing this and #474 internally. As @russellwheatley said, it would be great to have more customization, but we want to be careful with the number of params for this extension, given the level of customization that Sharp allows. I'm going to move this to the "blocked" state while we consider it.

**Comment by zeus3rd** [comment]
This option would be fantastic as it was an immediate disappointment I couldn't do this natively right now.

A better approach though would be to use some kind of extra string modifier in your current dimensions list (e.g. 200?x400?) so the image fits into at least one of these dimension values. This is really important when creating something like 40x40 user avatar image or 200x200 gallery preview image as we wouldn't want a user to manually select their own previews on upload (particularly during mass uploads)

**Comment by rolandszpond** [comment]
Hello, I would also like to be able to choose my "fit" type as well as being able to set the "withoutEnlargement" boolean. This makes sense because when I'm already setting the width and height of the desired output (ex. 300x300), but depending on the image if it's square or not, I'm getting unexpected results and not getting the image size that I've requested. Being able to set these two options would keep the current functionality of just sizing the image down, but also get more accurate results that I'm request, even if it's making the image bigger than the original.

As per the sharp documentation, I should be able to choose the "fit" to be either cover, contain, fill, inside, or outside. The "withEnlargement" would be either true/false.

https://github.com/firebase/extensions/blob/master/storage-resize-images/extension.yaml
