### ISSUE TITLE
Watermark on image upload

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [firebase/extensions#493]
This feature request is for extension: **\_** (`storage-resize-images`)

### What feature would you like to see?

I think if a watermark addition on the image as an option would be great,
For example:
* Image gets uploaded to the bucket from some service using it.
* The image then is watermarked if the developer requested so in the extension setup, of course, optional you could just turn it off.
* Then the resizing happens on the watermarked image.

### How would you use it?

I am making an app for showing your stuff to be sold locally, with no payment inside the app. Just advertising your things and comments and messages so people could communicate with you. I would want the images uploaded to have the logo watermarked on the bottom right corner so photos are not usable by other websites or services, for protecting the stuff that the user uploads and advertises for my service also. I think it will be a great addition to the plugin.

**Comment by russellwheatley** [comment]
Hi @YazeedAlKhalaf, thanks for the suggestion. This request seems a little outside the scope of this extension. The FE team will get back to you with a response in due course.

**Comment by jhuleatt** [comment]
Thanks for the suggestion @YazeedAlKhalaf! This adds more complexity to `storage-resize-images` than we'd like, since it's outside that extension's core purpose of resizing images. However, we've filed this internally as a request for a new extension for watermarking images. 

In the meantime, you can build this yourself with Cloud Functions for Firebase. There are some hints in [this Stack Overflow answer](https://stackoverflow.com/a/62410008/4816918).
