### ISSUE TITLE
auth-mailchimp-sync with upgraded users for anonymous to a user with email

### ISSUE THREAD

**Issue by perryjsteward** [firebase/extensions#496]
### What feature would you like to see?

I use anonymous users to store unauthenticated user data in my RTDB so that when the user does sign in they keep all their data. I then use the link operation to upgrade anonymous user to one with email.  

### How would you use it?
On this upgrade i would like to sync the email with Mailchimp.

**Comment by russellwheatley** [comment]
Hey @perryjsteward, thanks for the feature request. it is currently not possible to update Mailchimp if a user initially logs in as anonymous as described [here](#478).  

I'd advise tracking this [issue](#415) for further updates on backfilling  Mailchimp with users who aren't on the mailing list because, for instance, they initially signed up as anonymous.
