### ISSUE TITLE
Extension: Trigger E-Mail, Feature: Flag rejectUnauthorized 

### ISSUE THREAD

**Issue by erostefano** [firebase/extensions#497]
### Checkbox for flag rejectUnauthorized

This feature request is for extension:  (`Trigger E-Mail`)

### What feature would you like to see?

A checkbox to enable or disable the flag `rejectUnauthorized ` in the Trigger E-Mail environment.

### How would you use it?

The thirdparty smtps server uses a Shared Certificate which doesnt include my hostname in the altnames - and never will. Because this of this I get the following error message when sending mails:
`Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames`.

Setting the flag `{ rejectUnauthorized : false }` would solve this problem.

**Comment by russellwheatley** [comment]
Hey @erostefano, thanks for the feature request. Here is the [option](https://nodemailer.com/smtp/#tls-options) in the nodemailer documentation that would be implemented. I'm sure the Firebase Extension's team will consider this feature and get back to you.

**Comment by jhuleatt** [comment]
Hi @erostefano, thanks for the request! This sounds like it would be pretty easy to implement. However, we're also wary of increasing the number of parameters on an extension, since it makes the initial install experience more complex for developers new to the extension. We're going to hold off on implementing this until at least one other person requests similar functionality.

For anyone with a similar issue that's reading this: if you'd like this feature, please comment below!

**Comment by aabc123** [comment]
Yes we're hitting this too.  Is there are work-around?

**Comment by aabc123** [comment]
Ours may be due to our SMTP login having to be the full e-mail address of the account (including the @).  I don't think the extension likes the SMTP string having 2 @s in it.  I think it's using the e-mail address domain as the server, not the actual server we've entered.

Has anyone else got this issue?  Or could the parsing be improved to look for the last @ to find the server?

**Comment by rhymer211** [comment]
Yes we're hitting this too.

**Comment by L96Github** [comment]
Also needing that `rejectUnauthorized ` parameter to avoid getting
`Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames`

This is due to the SMTP server set-up but we are unable to change that set up at the moment...
Thanks

**Comment by pumanitro** [comment]
I don't get it. It was working a week ago and now it stopped due to this error. So strange, but I've got it too and would like to solve it.

**Comment by pumanitro** [comment]
As a temporary solution I have removed plugin at all and used nodemailer (https://nodemailer.com/smtp/#tls-options) node plugin for this. There is almost identical configuration so small effort was needed to accomplish it. Ofc I had to add this flag `{ rejectUnauthorized : false }`

**Comment by ElaineSchwner** [comment]
Hi, I face the same problem.
It would be great to have a work around.

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: mail.7minutespay.com. is not in the cert's altnames: DNS:ag7m.ag7m.com

**Comment by debungle-it** [comment]
Hi, we are facing this too - basically anyone who has a hosted domain will run into this problem, as the SSL cert for the mail server will not match the sender domain.

In mail clients like Thunderbird you can add the security exception and ignore the mismatch **and still send the mail via a secure channel.** Right now our only option is unencrypted, obviously not a good idea.

**Comment by berkman** [comment]
I'm getting this error when trying to Trigger an Email via SendGrid when running the emulator on localhost
