### ISSUE TITLE
Document import script wildcard limitation

### ISSUE THREAD

**Issue by jhuleatt** [firebase/extensions#501]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **`firestore-bigquery-export`** 

### What feature would you like to see?

Document the fact that the backfill script doesn't support wildcards (details in https://github.com/firebase/extensions/issues/484#issuecomment-722278642), both in the [guide](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md) and in the import script's error message.

If possible, also document a workaround (although not sure there is a good one).

**Comment by jhuleatt** [comment]
@fredzqm @IanWyszynski any suggestions on a workaround for this limitation? Is there a (hacky?) way to work around this limitation?

**Comment by samtstern** [comment]
So in #484 the developer wants to refer to the collection `objects/{object}/list` which I interpret to mean all of the `list` subcollections belonging to any `objects` document.  This is the syntax used in Cloud Functions to capture events like that.

In Firestore all of those collections belong to the `list` collectionGroup.  So you could maybe modify the extension to have support for collectionGroups?  You'd have to warn developers though because accepting the exact syntax proposed would be innacurate.  A collectionGroup query for `list` would query all collections named `list` anywhere in the entire document/collection hierarchy.  There's no way to specify that you want the parent collection to be `objects` or even that the depth of the subcollection should be 3.

**Comment by russellwheatley** [comment]
The import script supports `collectionGroup` queries #354. The documentation could definitely be improved, perhaps indicating this limitation and the recommended workaround. This issue has cropped up a few times.

**Comment by jhuleatt** [comment]
@russellwheatley can you please create a PR with a draft for a docs update and set @kevinthecheung as reviewer?
