### ISSUE TITLE
storage-resize-images: allow to specify a specific size for a specific path

### ISSUE THREAD

**Issue by kuamanet** [firebase/extensions#552]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`
### What feature would you like to see?

I'd like to specify one (or more) size on a per-path basis

### How would you use it?

I would generate different image resolutions for different content types (ex. artwork content type vs category content type)

**Comment by russellwheatley** [comment]
Hey @kuamanet, thanks for the suggestion. We're wary of increasing the number of parameters for each extension, particularly one that has 7 already. If anyone else who would like to see this feature, please leave a comment below so we can see how popular it is!

In the mean time, I would suggest that what you want is already possible. You could just create a `storage-resize-image` extension for each image size(s), and use the include and exclude path [options](https://github.com/firebase/extensions/blob/next/storage-resize-images/README.md#additional-setup) to specify which images ought to be resized.

**Comment by chrisjacobs91** [comment]
@russellwheatley I would also find this useful. I am about to setup separate instances of the extension for different image paths, but from how I understood the documentation, the include/exclude fiedlds only match specific file paths.

My folder structure is: 
/profile/{userID}/photos/{photoID}/photo.jpg
/recipe/{recipeID/photos/{photoID}/photo.jpg

Can I simply put /profile in my include list to include ANY images uploaded to any children folders underneath the /profile path?

**Comment by russellwheatley** [comment]
@chris Yes, that is correct.

**Comment by chrisjacobs91** [comment]
can confirm this works and feels like a perfectly good solution to this problem. personally I wouldn't want this feature to be prioritised over some of the other requests :)

**Comment by WesselvanDam** [comment]
Hello, I have a similar question so that's why I'm commenting here instead of opening a new issue. In my app users can upload a profile picture, but to prevent the storage from getting too full I want to resize the image twice: once to a 600x600 size and once to a thumbnail size of 64x64. My storage file structure is as follows:

/avatars/original/photo_600x600.jpg
/avatars/thumbnail/photo_64x64.jpg

Since the feature requested in this issue isn't available, I tried to install the extension twice. The sequence I had in mind was:

1.  User uploads a picture, it gets placed in `/avatars/`.
2. Extension 1 (looking for uploads in `/avatars/`) resizes it to 600x600 and places it in `/avatars/originals/`
3. Extension 2 (looking for uploads in `/avatars/original`) resizes it to 64x64 and places it in `/avatars/thumbnail`.

Step 1 and 2 work, but Extension 2 doesn't seem to recognize files placed there by Extension 1. If I upload directly to `/avatars/originals/`, Extension 2 does recognize it. 

I prefer not to do two upload operations, but I also can't have both Extensions resizing the original image in `/avatars/` because I want to delete that original image afterwards. If I set the extensions to delete it after succesful conversion, it might be so that the one Extension is not finished yet when the other already deletes it. What is the best approach for this?

**Comment by WesselvanDam** [comment]
Tests with an implementation where both extensions resize the same file and delete it on success seem to work; can anyone tell me whether this is safe enough?

**Comment by i14h** [comment]
@karayu what do you think about this feature? should we implement native support for the feature like in #553 or should we turn this into a hook so users can take over destination file path logic and implement any custom logic they want?

**Comment by dackers86** [comment]
For this feature, EventArc has been provided as a way for developers to have control over the resized images.

```
The extension can publish a resize completion event which you can optionally enable when you install the extension. If you enable events, you can [write custom event handlers](https://firebase.google.com/docs/extensions/install-extensions#eventarc) that respond to these events. You can always enable or disable events later. Events will be emitted via Eventarc.
```

Source: https://github.com/firebase/extensions/blob/next/storage-resize-images/README.md

Closing this issue for now.
