### ISSUE TITLE
Duplicate records when mirroring data to BigQuery

### ISSUE THREAD

**Issue by guilhermeagostinelli** [firebase/extensions#608]
- Extension name: `firestore-bigquery-export`
- Extension version: v0.1.12

It was running perfectly fine on v0.1.5 but after upgrading to v0.1.12 the extensions started to export duplicated records to BigQuery.

The only difference between two duplicate records is the `document_id` field: one of the records has a null `document_id` and the other has a non-null `document_id`.

It's a very severe problem since it compromised many of my reports.

Weirdly, not all the records are getting duplicated. Sometimes they do and sometimes they do not - and whey they don't, there's only one record: the one with the non-null `document_id`. Still, this is a very frequent issue and since then I already have thousands of duplicates.

It's also worth mentioning that all of my extensions have been upgraded almost at the same time and that some of them are working perfectly.

**Comment by guilhermeagostinelli** [comment]
Update: I've tried uninstalling and installing the extension again and it still doesn't work. Duplication persists.

**Comment by guilhermeagostinelli** [comment]
What worked for me was:

1. Delete the whole dataset in BigQuery
2. Re-install the extension
3. Recover the previous records by executing the back-filling script

and now the extension stopped generating duplicates (0 new records with a null `document_id`).

**Comment by dackers86** [comment]
Thanks for the feedback @guilhermeagostinelli. 

I'm glad it's working. I'll close this issue for now, happy to reopen for further investigation / documentation that may be needed.

**Comment by raubrey2014** [comment]
@dackers86 documenting a similar issue here.

We have been using the firebase export extension for some time - v0.1.5 similarly before recently to v0.1.12. It seems that in between that time, the `document_id` field was added to the underlying `<your exported collection name>_raw_changelog` table, as well as the `<your exported collection name>_raw_latest` view. [See here](https://github.com/firebase/extensions/commit/1899a56952bbcdb589b42f1561cce047d8361901#diff-4543f4f9494d3f500982c8927ccc111dfd58df89a38b02b5106cdbcfe445ba0f).

This presents an issue for collections that have been exporting from before this change to after -


Before (looks like before v0.1.7): there is no document_id included in _raw_changelog, but it doesn't matter because _raw_latest only groups by document_name. Great.

After: now there is a field document_id included in _raw_changelog, and it matters because now _raw_latest groups by both document_name and document_id. That means if we have any rows in the changelog that are for the same document (same document_name), but one was ingested before the update (meaning before document_id was added, so document_id is null) and one ingested after the update (document_id now has a value), we get two rows for the document.

Have you seen other teams encounter this issue? I think a possible solution could just be to backfill the entries ingested before v0.1.7, so that those ingested rows have a document_id. Any help is much appreciated!

**Comment by dackers86** [comment]
@raubrey2014.


Although not common, there does seem to be an issue with missing document Ids. I feel you are correct that this could be potentially fixed by backfilling missing document Ids. I will reopen for investigation

**Comment by raubrey2014** [comment]
@dackers86 just as a follow up, yes I backfilled the entries to fix this discrepancy.

For anyone else running into this issue, I backfilled by the query below, but you **should be very careful** when doing this. This query assumes that the last 20 characters of the column `document_name` are the document id. There could be cases where that is not a safe assumption.

```
UPDATE `<your project id>.<your dataset id>.<exporter collection name>_raw_changelog` SET document_id=RIGHT(document_name, 20) WHERE document_id IS NULL;
```

So for me it looks something like:

```
UPDATE `ryans_project.firestore.comments_raw_changelog` SET document_id=RIGHT(document_name, 20) WHERE document_id IS NULL;
```

Hope this is helpful!

**Comment by guilhermeagostinelli** [comment]
In my case, since I deleted the whole dataset, after reinstalling the extension I backfilled the new dataset with all the documents in my collection by running the [import script](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md) provided by the extension.

But that might be troublesome if you have too many records, so @raubrey2014 's suggestion sounds better.

Extending @raubrey2014 's answer, a regular expression can be used so one doesn't need to worry with the length of the 'document_name' field when performing the update operation:

```sql
UPDATE `<your project id>.<your dataset id>.<exported collection name>_raw_changelog` SET document_id = REGEXP_EXTRACT(document_name, r"([^\/]+$)") WHERE document_id IS NULL;
```

**Comment by jhuleatt** [comment]
@russellwheatley this sounds like it's due to the `document_id` breaking change from a little while ago. Am I correct in saying the only fix for this is to backfill with the import script?

**Comment by russellwheatley** [comment]
That is correct. The BQ extension will also try and insert the `document_id` column [here](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L237-L240), but I guess the best bet is to use the import script which will run the same method and won't crash the cloud function. This is because the schema change takes a while to percolate through the BigQuery system.

**Comment by dackers86** [comment]
Closing as this appears to be resolved.
