### ISSUE TITLE
[Question] Does the firestore-bigquery-export incur egresss costs (fs-bq-import-collection)

### ISSUE THREAD

**Issue by lethrez** [firebase/extensions#922]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-bigquery-export specifically for npx @firebaseextensions/fs-bq-import-collection

### What feature would you like to see and how would you use it?

When running this extension locally it isn't entirely clear if GCP egress costs are incurred.
I've been quite enjoying this extension and looking to import larger collections / terabytes + to populate historical / current state.
Is it worth spinning this up over VMs etc in GCP or running the extension locally is fine?

**Comment by lethrez** [comment]
I imagine the main cost will be the .60c per 1 mil reads on firestore, but worth considering.

**Comment by Salakar** [comment]
When running the export script locally Firestore data is read to your local machine, and then data transferred from local machine to BigQuery - so I Imagine there would be egress costs here.

Perhaps egress costs can be avoided by running the export script inside a GCP container, maybe via a Cloud Shell instance in the same region if you're expecting large costs due to egress

**Comment by lethrez** [comment]
Thanks @Salakar!
