### ISSUE TITLE
[Firebase-trigger-email] Logs too verbose, logging template loads

### ISSUE THREAD

**Issue by DCSnip3r** [firebase/extensions#944]
The logs of this extension are too verbose. If I send one email, it loads and logs each email template I have. Logging which templates have been loaded, especially ones that are irrelevant to the email at hand, is not necessary.

**Comment by i14h** [comment]
This is good feedback. @dackers86 can we review how we log these steps?

**Comment by dackers86** [comment]
This appears to occur on the `Templates` class constructor when the function is first initialised.

The reason it logs individually is because of a series of checks on each template.

```js
    templates.forEach((t) => {
      const tgroup: TemplateGroup = {};
      if (t.subject) {
        tgroup.subject = subjHandlebars.compile(t.subject, { noEscape: true });
      }
      if (t.html) {
        tgroup.html = htmlHandlebars.compile(t.html);
      }
      if (t.text) {
        tgroup.text = textHandlebars.compile(t.text, { noEscape: true });
      }
      if (t.amp) {
        tgroup.amp = ampHandlebars.compile(t.amp);
      }
      if (t.attachments) {
        tgroup.attachments = attachmentsHandlebars.compile(
          JSON.stringify(t.attachments),
          { strict: true }
        );
      }

      this.templateMap[t.name] = tgroup;

     // Individual log occurs here!
      templateLoaded(t.name);
    });
```

Perhaps this log could be moved outside of the forEach to log after the checks have been completed.

This could also be  updated to map and provide a single log to show all `valid` templates in one comma separated list.
